Fix reconnect
bitfinexcom/bitfinex-api-node pull request #571
Opened 2021-04-22 16:58 UTC by vitaliystoliarovcc

### Description:
The problem is that while saving the creds in Settings, the API key and secret were not dynamically changed in WS2. When reconnecting, it still used the old ones. 

### Fixes:
- Fix ignored authArgs on reconnect

https://user-images.githubusercontent.com/70510980/115753939-62a6e180-a3a4-11eb-8517-df1ae0b9e258.mov

2021-04-26 14:59 UTC, robertkowalski requested changes
can you add tests?

2021-04-26 16:03 UTC, vitaliystoliarovcc commented
@robertkowalski 
> can you add tests?
What kind of tests? I have not changed the current functionality, therefore I only updated the tests, no other unit tests need to be added

> can you also share an example to reproduce the issue with library standalone?
Didn't find any integration tests for this library. Tested only in conjunction with HF UI

2021-04-26 18:41 UTC, tarcisiozf approved these changes
lgtm

2021-04-26 18:45 UTC, tarcisiozf commented
regarding the tests maybe you could stub the prototype.auth method with sinon and ensure that it was called when reconnecting to avoid someone breaking this by mistake in the future.

2021-04-27 07:47 UTC, robertkowalski commented
we have a mock server that can serve common responses, but some tests also use a custom server.

here is an example: https://github.com/bitfinexcom/bitfinex-api-node/blob/master/test/lib/transports/ws2-integration.js#L44

2021-04-28 11:04 UTC, vitaliystoliarovcc commented
Test failed because it requires changes from bitfinexcom/bfx-api-mock-srv#48

2021-04-28 12:07 UTC, merged

2021-04-28 12:07 UTC, robertkowalski commented
lgtm, nice test! 👍